name: Git Auto Semver Tag

on:
  push:
    branches:
      - master

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - uses: pranart/Git-Automatic-Semver-Tagging@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
