name: Git Auto Semver Tag

on:
  push:
    branches: [ main ]

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - uses: ArvindSinghRawat/Git-Automatic-Semver-Tagging@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
